services:
  metal-adventures:
    build:
      context: .
      args:
        CACHEBUST: ${CACHEBUST:-1}
    ports:
      - "3200:3000"
    volumes:
      - ./db:/app/db
      - ./uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - DB_PATH=./db/ma.db
      - PORT=3000
    restart: unless-stopped
